spring:
  data:
    redis:
      host: redis
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ecommerce
          jwk-set-uri: http://keycloak:8080/realms/ecommerce/protocol/openid-connect/certs

eureka:
  instance:
    hostname: api-gateway
  client:
    service-url:
      defaultZone: http://eureka:eureka@discovery-server:8761/eureka/
